### ISSUE TITLE
Spring Cloud Contract cannot convert unicode string in contract.yml

### ISSUE THREAD

**Issue by halucki** [spring-cloud/spring-cloud-contract#1038]
I want JSON files for WireMock stubs from contract files written by YAML.
But Spring Cloud Contract Gradle Plugin cannot convert contract files correctly when it contains unicode strings (e.g."日本").
(I'm generating stubs by executing "generateClientStubs" task of Gradle plugin.)

Specifically, I made the following contract yaml file.

```
name: get-all-users
request:
url: /users
method: GET
response:
status: 200
headers:
    content-type: application/json; charset=UTF-8
body:
    -
    id: 001
    name: alice
    country: US
    - 
    id: 002
    name: bob
    country: 日本
```

And after doing generateClientStubs task I got the following JSON file.

```
{
 "id" : "b776c7d1-fd6d-454a-be92-ef02b8eec793",
 "request" : {
     "url" : "/users",
     "method" : "GET"
 },
 "response" : {
     "status" : 200,
     "body" : "[{\"id\":1,\"name\":\"alice\",\"country\":\"US\"},{\"id\":2,\"name\":\"bob\",\"country\":\"\\u65e5\\u672c\"}]",
     "headers" : {
     "content-type" : "application/json; charset=UTF-8"
     },
     "transformers" : [ "response-template" ]
 },
 "uuid" : "b776c7d1-fd6d-454a-be92-ef02b8eec793"
}
```

As you can see, unicode strings of response body(especially "country\":\"\u65e5\u672c\" part) are not converted correctly. What I want is as follows:

```
"body" : "[{\"id\":1,\"name\":\"alice\",\"country\":\"US\"},{\"id\":2,\"name\":\"bob\",\"country\":\"日本"}]"
```
I must handle with Japanese strings like that (cause I'm Japanese...).
How can I solve them?

Thank you for reading.
