### ISSUE TITLE
integer number too large: 1541609556000

### ISSUE THREAD

**Issue by benoitheinrich** [spring-cloud/spring-cloud-contract#1052]
Bug report

I'm using spring-cloud-contract 2.1.1-RELEASE.

When I create a contract like that:
```
request:
  url: /numbers
  queryParameters:
    page: 0
    size: 2
  method: GET
  headers:
    Content-Type: application/json

response:
  status: 200
  headers:
    Content-Type: application/json;charset=UTF-8
  body:
    - number: 1541609556000
    - number: 1541609316000
  matchers:
    body:
      - path: $.[0].number
        type: by_equality
      - path: $.[1].number
        type: by_equality
```

It generates the following code:
```
  @Test
  public void validate_someTest() throws Exception {
    // given:
      RequestSpecification request = given()
          .header("Content-Type", "application/json");

    // when:
      Response response = given().spec(request)
          .queryParam("page","0")
          .queryParam("size","2")
          .get("/numbers");

    // then:
      assertThat(response.statusCode()).isEqualTo(200);
      assertThat(response.header("Content-Type")).isEqualTo("application/json;charset=UTF-8");
    // and:
      DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
      assertThatJson(parsedJson).array().contains("['number']").isEqualTo(1541609316000L);
    // and:
      assertThat(parsedJson.read("$.[0].number", Long.class)).isEqualTo(1541609556000);
      assertThat(parsedJson.read("$.[1].number", Long.class)).isEqualTo(1541609316000);
  }
```

This code doesn't compile due to:
```
integer number too large: 1541609316000
```

In fact that test is checking a `Long` type but uses an integer notation.
It should add the `L` suffix to force the Long conversion.

The generated code should contain the following:
```
      assertThat(parsedJson.read("$.[0].number", Long.class)).isEqualTo(1541609556000L);
      assertThat(parsedJson.read("$.[1].number", Long.class)).isEqualTo(1541609316000L);
```

Thanks for looking at this.
