### ISSUE TITLE
Spring cloud contract stub runner - no way to customize embeded wiremock?

### ISSUE THREAD

**Issue by JulianAffaire** [spring-cloud/spring-cloud-contract#1255]
Hi,

I tried to launch stubrunner as standalone thanks to spring boot :

```java
@SpringBootApplication
@EnableStubRunnerServer
public class StubRunnerBootApplication {
	public static void main(String[] args) {
		SpringApplication.run(StubRunnerBootApplication.class, args);
	}
}
```

```
stubrunner:
      workOffline: true
      cloud.stubbed.discovery.enabled: false
      ids: com.myapp.service:my-stub:1.0.0:stubs:8385
      stubs-mode: local
      httpServerStubConfigurer: com.myapp.service.WiremockCustomConfiguration
```
You can see I added "httpServerStubConfigurer" :

```java
public class WiremockCustomConfiguration extends WireMockHttpServerStubConfigurer {
	@Override
	public WireMockConfiguration configure(WireMockConfiguration httpStubConfiguration, HttpServerStubConfiguration httpServerStubConfiguration) {
		httpStubConfiguration.asynchronousResponseEnabled(true);
		httpStubConfiguration.asynchronousResponseThreads(20);
		httpStubConfiguration.containerThreads(100);
		httpStubConfiguration.jettyAcceptors(10);
		httpStubConfiguration.jettyAcceptQueueSize(100);
		httpStubConfiguration.jettyHeaderBufferSize(16384);
		httpStubConfiguration.disableRequestJournal();
	}
}
```

In debug mode I can see this configuration is well executed but wiremock seems to not use those custom parameters :( . Is there an other way to customize Wiremock configuration ?

Thanks,
Julian
