### ISSUE TITLE
Response body matchers only works if response body is defined

### ISSUE THREAD

**Issue by aziouiz** [spring-cloud/spring-cloud-contract#1261]
**Bug report:**
I am using the dependency org.springframework.cloud:spring-cloud-starter-contract-verifier:2.1.3.RELEASE with the plugin org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.3.RELEASE.
When I specify body matchers without body in the response the assertion on the numberField is not generated.
 
I have the following cdc file 
```yaml
request:
  method: GET
  url: /bug
response:
  status: 200
  matchers:
    body:
      - path: $.numberField
        type: by_regex
        value: as_integer
---
request:
  method: GET
  url: /works
response:
  status: 200
  body:
    #The matchers on the body only work if the body is at least tested for one field.
    hackField: null
  matchers:
    body:
      - path: $.numberField
        type: by_regex
        value: as_integer
```

The generated test class is : 
```java
public class BugTest extends ContractBaseTest {

	@Test
	public void validate_spring_cdc_bug() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();

		// when:
			ResponseOptions response = given().spec(request)
					.get("/bug");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
	}

	@Test
	public void validate_spring_cdc_bug_1() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();

		// when:
			ResponseOptions response = given().spec(request)
					.get("/works");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['hackField']").isNull();
		// and:
			assertThat(parsedJson.read("$.numberField", String.class)).matches("as_integer");
	}

}```
