### ISSUE TITLE
jsonpath wildcard with collection returns a string

### ISSUE THREAD

**Issue by JosephGaiser** [spring-cloud/spring-cloud-contract#1344]
Hello 👋 
I am trying to reference the request to build out the body of my response using jsonpath. I want the response to have the same collection as the one sent in the request. The issue is that I am getting back a string instead of a collection. Is there something I am doing wrong or is there not a way to reference the request body with jsonpath without getting back a string?

**Response Section of Contract**
```
response:
  status: 201
  body:
    id: "4ADD5DD9-8290-4B9D-861F-66E16B96AEA4"
    name: "{{{ jsonpath this '$.name' }}}"
    myCollection: "{{{ jsonpath this '$.myCollection.*' }}}"
```

**Request**
```
{
  "name": "Joe",
  "myCollection": [
    {
      "foo": "12345",
      "bar": true
    },
    {
      "foo": "54321",
      "bar": false
    }
  ]
}
```

**Response**
```
{
  "id": "4ADD5DD9-8290-4B9D-861F-66E16B96AEA4"
  "name": "Joe",
  "myCollection": "[{"foo": "12345","bar": true},{"foo": "54321","bar": false}]"
}
```
`myCollection` is a string not a collection ☝️ 
`YAML DSL version: 2.2.2.RELEASE`
