### ISSUE TITLE
Defining matchers causes impossible producer test to be genereated

### ISSUE THREAD

**Issue by JosephGaiser** [spring-cloud/spring-cloud-contract#1414]
### Issue
When you define a matcher for every field in the body of a response the following producer test is generated that is impossible to pass: `assertThatJson(parsedJson).array().isEmpty();`
I believe the body must be a collection for this issues to occur.

### Sample to reproduce
Contract:
```
name: GET sample
description: sample
request:
  method: GET
  urlPath: /sample
response:
  status: 200
  body:
    - foo: "sample1"
      bar: true
    - foo: "sample2"
      bar: false
  headers:
    Content-Type: application/json
  matchers:
    body:
      - path: $..foo
        type: by_regex
        value: .*
      - path: $..bar
        type: by_regex
        predefined: any_boolean
```
Generated Producer Tests:
```
@Test
public void validate_gET_sample() throws Exception {
	// given:
		WebTestClientRequestSpecification request = given();


	// when:
		WebTestClientResponse response = given().spec(request)
				.get("/sample");

	// then:
		assertThat(response.statusCode()).isEqualTo(200);
		assertThat(response.header("Content-Type")).isEqualTo("application/json");

	// and:
		DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
		assertThatJson(parsedJson).array().isEmpty();

	// and:
		assertThat((java.lang.Iterable) parsedJson.read("$..foo", java.util.Collection.class)).as("$..foo").allElementsMatch(".*");
		assertThat((java.lang.Iterable) parsedJson.read("$..bar", java.util.Collection.class)).as("$..bar").allElementsMatch("(true|false)");
}
```
`Version 2.2.2.RELEASE`
