### ISSUE TITLE
Contract to return empty collection generates incorrect producer test / NPE

### ISSUE THREAD

**Issue by JosephGaiser** [spring-cloud/spring-cloud-contract#1423]
### Issue
Contracts for returning an empty collection will throw a NPE when generating producer side tests.
When using a workaround to prevent the NPE you will encounter the following issue.
A test will be generated for the contract that does not assert that the collection is empty. Instead it will only assert the status code returned.

### Sample to recreate incorrect test
```
description: Returns an empty collection
request:
  method: GET
  urlPath: /foo
  queryParameters:
    someId: 1234
response:
  status: 200
  bodyFromFile: bodies/EmptyCollectionResponse.json
```
`bodies/EmptyCollectionResponse.json` being  `[]` 
```
@Test
public void validate_foo_1() throws Exception {
	// given:
		WebTestClientRequestSpecification request = given();


	// when:
		WebTestClientResponse response = given().spec(request)
				.queryParam("someId","1234")
				.get("/foo");

	// then:
		assertThat(response.statusCode()).isEqualTo(200);


	// and:
		DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
}
```
I believe this test should include `assertThatJson(parsedJson).array().isEmpty();` in the `// and` block.

### Sample to reproduce the NPE
```
description: Returns an empty collection
request:
  method: GET
  urlPath: /foo
  queryParameters:
    someId: 1234
response:
  status: 200
  body:
    -
```

exception from `gradle clean generateContractTests`:
```
ask :generateContractTests FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateContractTests'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
3 actionable tasks: 3 executed
```
`Version 2.2.2.RELEASE`
