### ISSUE TITLE
Test spring cloud stream functions

### ISSUE THREAD

**Issue by aariza1** [spring-cloud/spring-cloud-contract#1521]
**Version:** Hoxton SR8 -> spring cloud contract 2.2.4.RELEASE

**Description**
we are trying to implement spring cloud contracts for messaging (kafka) from consumer perspective. We are having issues trying to figure out how to create messages in the tests on given topic using the consumer functions from our production code.

**Sample**
Here's an example [project](https://github.com/FlxGschlr/demo-sender)

Could you please add an example of the recommended approach or best practice?

best regards

**Comment by marcingrzejszczak** [comment]
Here you have an example using Spring Cloud Stream - https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/consumer

Here you have an example with plain Kafka https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/consumer_kafka

Here you have an example with Kafka running in test containers https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.0.x/consumer_kafka_middleware

**Comment by aariza1** [comment]
I guess I asked the question wrong, sorry about that. 

We are talking about how spring cloud contracts test should work with functions.
We did not find any samples that use spring cloud function programming model.

Please see the test supplier class in our application.yml


```
    spring:
      cloud:
        stream:
          bindings:
            exampleEventsSupplier-out-0:
              destination: examples
        function:
          definition: exampleEventsSupplier
```

```
@Configuration
class TestSupplier {

    ...

    @Bean
    fun exampleEventsSupplier(): Supplier<Flux<Message<ExampleEvent>>> = Supplier {
        processor
                .map { it.toMessage() }
                .doOnNext { logger.info { "Sent $it" } }
    }

    private fun ExampleEvent.toMessage() = MessageBuilder
            .withPayload(this)
            .build()
}
```

**Comment by OlgaMaciaszek** [comment]
Please check the provided [consumer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/3.0.x/consumer/src/main/java/com/example/BeerVerificationListener.java) and [producer](https://github.com/spring-cloud-samples/spring-cloud-contract-samples/blob/3.0.x/producer/src/main/java/com/example/AgeCheckingPersonCheckingService.java) examples. They use Spring Cloud Stream, that uses Spring Cloud Function.

**Comment by aariza1** [comment]
Thank you for your answer but that is not the point. The question is: 
How to write spring cloud contracts using spring cloud functions?
We could not find contracts in the provided examples.

**Comment by marcingrzejszczak** [comment]
I think we have a communication problem here. You're showing that you're using Spring Cloud Stream with Spring Cloud Function

```yml
    spring:
      cloud:
        stream:
          bindings:
            exampleEventsSupplier-out-0:
              destination: examples
        function:
          definition: exampleEventsSupplier

```

We're showing you 2 examples (consumer & producer) for Spring Cloud Contract that works with Spring Cloud Stream with Spring Cloud Function.

I don't understand the problem.
