### ISSUE TITLE
Contract to return collection with null element generates NPE

### ISSUE THREAD

**Issue by bono007** [spring-cloud/spring-cloud-contract#1557]
### Issue
Contracts for returning a collection with a single null element will throw a NPE when generating producer side tests.

(Split out from #1423)

### Sample to recreate incorrect test
```
description: Returns an empty collection
request:
  method: GET
  urlPath: /foo
  queryParameters:
    someId: 1234
response:
  status: 200
  body: 
    -
```

#### Details

Given this collection
```
[ null ]
```
this path should be valid:
```
$.[?(@ == null)]
```
And given this collection
```
[ 'a' , 'b', null, 'c' ]
```
these paths should be valid :
```
$.[?(@ == 'a')]
$.[?(@ == 'b')]
$.[?(@ == null)]
$.[?(@ == 'c')]
```

However, if `JsonVerifiable.isNull` is used it will currently generate:
```
$.[?(@. == null)]
```
which is invalid (notice the `.` after the `@`).

I attempted to work around this by using the following to generate `[?(@ == null)]`
```
assertThatJson(JsonPath.parse("[null]")).arrayField().matchesJsonPath("[?(@ == null)]")
```
While it did generate the proper json path, the evaluation fails w/ the following due to [this](https://github.com/marcingrzejszczak/jsonassert/blob/jsonassert-0.4.14/jsonassert/src/main/java/com/toomuchcoding/jsonassert/JsonAsserter.java#L227) as `containsEmptyElementsOnly(array)` evaluates to `true`. If we can lift that restriction then it would work. However, I am guessing its there for a very particular reason.
