### ISSUE TITLE
Successed/failed test in Windows/Linux due to \r\n

### ISSUE THREAD

**Issue by Daemon2017** [spring-cloud/spring-cloud-contract#1562]
**Describe the bug**
Hello, Marcin! 

I have a problem with my contract: the test is successful on my local PC (Win10), but it fails on my GitLab server (Linux-based) at 3rd check (\r\n):

> java.lang.IllegalStateException: Parsed JSON 
> [{"Text1":"Unexpected EOF in prolog\r at [row,col {unknown-source}]: [1,0].","Text2":"Unexpected EOF in prolog\n at [row,col {unknown-source}]: [1,0].","Text3":"Unexpected EOF in prolog\n at [row,col {unknown-source}]: [1,0]."}] 
>  doesn't match the JSON path 
> [$[?(@.['Text3'] == 'Unexpected EOF in prolog\r\n at [row,col {unknown-source}]: [1,0].')]]

As far as I understand, sign **\r** missed and it caused a mismatch. Is there a way to perform validation ignoring the platform format (LF / CRLF)?
Now my only idea is to use regex:
```
response:
  async: true
  status: 200
  headers:
    Content-Type: application/json
  body:
    Text1: 'Unexpected EOF in prolog\r at [row,col {unknown-source}]: [1,0].'
    Text2: 'Unexpected EOF in prolog\n at [row,col {unknown-source}]: [1,0].'
    Text3: $.Text3
  matchers:
    body:
      - path: $.Text3
        type: by_regex
        value: "(Unexpected EOF in prolog\n at [row,col {unknown-source}]: [1,0].|Unexpected EOF in prolog\r\n at [row,col {unknown-source}]: [1,0].)"
```

Versions:

> org.springframework.cloud.contract, 2.2.3.RELEASE
> org.springframework.cloud:spring-cloud-contract-dependencies, 2.1.3.RELEASE

**Sample**
My YAML-contract:
```
description: >
  rq rs
name: rq rs
request:
  method: POST
  url: /getError
  headers:
    Content-type: application/json
  body:
    RequestID: '1a'
response:
  async: true
  status: 200
  headers:
    Content-Type: application/json
  body:
    Text1: 'Unexpected EOF in prolog\r at [row,col {unknown-source}]: [1,0].'
    Text2: 'Unexpected EOF in prolog\n at [row,col {unknown-source}]: [1,0].'
    Text3: 'Unexpected EOF in prolog\r\n at [row,col {unknown-source}]: [1,0].'
```

My Wiremock-mock:
```
{
  "request": {
    "method": "POST",
    "url": "/getError",
    "headers": {
      "Content-type": {
        "equalTo": "application/json; charset=UTF-8"
      }
    },
    "bodyPatterns": [
      {
        "equalToJson": "{\"RequestID\":\"1a\"}"
      }
    ]
  },
  "response": {
    "status": 200,
    "body": "{ \"Text1\":\"Unexpected EOF in prolog\\r at [row,col {unknown-source}]: [1,0].\", \"Text2\":\"Unexpected EOF in prolog\\n at [row,col {unknown-source}]: [1,0].\", \"Text3\":\"Unexpected EOF in prolog\\r\\n at [row,col {unknown-source}]: [1,0].\" }",
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": [
      "response-template"
    ]
  }
}
```
