### ISSUE TITLE
Contract Verifier with SCSt doesn't receive messages

### ISSUE THREAD

**Issue by lz101010** [spring-cloud/spring-cloud-contract#1626]
**Describe the bug**
I have a component that sends a message via a running RabbitMQ to another component. In my contract test I trigger the producing component and see that the consuming component receives that message - but I'm unable to properly hook up the verifier to confirm this.

I'm using the following setup:
- Spring Boot 2.4.3
- Spring Cloud Stream 3.1.1 (including rabbit binder)
- Spring Cloud Contract Verifier 3.0.1

Unless I do the following, the generated contract test isn't able to verify the message has been received:
- explicitly `@MockBean` the component to which the message is sent (otherwise that component consumes the message and `ContractVerifierMessaging` fails to receive it with a NPE)
- use a specific channel name value in order for `ContractVerifierMessaging` to subscribe to that channel (otherwise I get `Dispatcher has no subscribers for channel 'application.desired-channel-name'` and subsequently a NPE)

I'm not using SCSt's test binder in order to have true integration tests, because routing keys are relevant. What I've been able to verify:
- I can see the messages in RabbitMQ's UI and that the component to which the message is sent receives it (unless I `@MockBean` it)
- I can run my own integration tests where I spy on the receiving component to verify the receipt (without the workarounds mentioned above)
- I don't have the above issues if I do a more manual setup via Spring AMQP instead of SCSt (using `@RabbitListener` instead of `@StreamListener` etc.)

**Sample**
Repo: https://github.com/lz101010/scc-messaging-triggeredby-method
Most relevant code:
<details>
  <summary>Contract Test</summary>

  ```java
Contract.make {
    label "notify admin"
    input {
        triggeredBy('notifyAdmin()')
    }

    outputMessage {
        sentTo("notifications")
        body([
                "message": "foobar"
        ])
        headers {
            header("amqp_receivedRoutingKey", "admin")
        }
    }
}
  ```
  </details>
<details>
  <summary>Contract Test Base Class</summary>

```java
@SpringBootTest(classes = ExampleApplication.class)
@AutoConfigureMessageVerifier
@RabbitAvailable
public abstract class NotificationBase {
    // need to mock the MessageReceiver bean in the application context to effectively ignore messages sent by messageSender
    @MockBean
    protected MessageReceiver messageReceiver;

    @Autowired
    protected MessageSender messageSender;

    protected void notifyAdmin() {
        messageSender.notifyAdmin("foobar");
    }
}
```
</details>
<details>
  <summary>Working Test</summary>

```java
@SpringBootTest(classes = ExampleApplication.class)
@RabbitAvailable
final class MessagingTests {
    protected final static String DUMMY_MESSAGE = "foobar";
    protected final static ExampleMessage DUMMY_EXAMPLE_MESSAGE = new ExampleMessage(DUMMY_MESSAGE);

    @SpyBean
    protected MessageReceiver messageReceiver;

    @Autowired
    protected MessageSender messageSender;

    @Test
    void testAdminNotification() {
        messageSender.notifyAdmin(DUMMY_MESSAGE);

        verify(messageReceiver, timeout(1000)).receiveAdminNotification(DUMMY_EXAMPLE_MESSAGE);
    }
}
```
</details>
<details>
  <summary>Messaging Components + Data</summary>

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExampleMessage implements Serializable {
    @NotBlank
    private String message;
}

public interface MessageChannels {
    // no idea why this particular name is needed for the channel to be created when running the contract tests
    // other names that work: a-b-c, w-a-t, admin-cin
    // other names that dont: admin-in, a-b, v1-admin-in
    public static final String ADMIN_IN = "v2-admin-in";
    public static final String ADMIN_OUT = "admin-out";

    @Input(ADMIN_IN) 
    MessageChannel adminNotificationsIn();

    @Output(ADMIN_OUT) 
    MessageChannel adminNotificationsOut();
}

@Component
@Slf4j
public class MessageReceiver {
    @StreamListener(MessageChannels.ADMIN_IN)
    public void receiveAdminNotification(ExampleMessage message) {
        log.info("Received admin notification: {}", message);
    }
}

@Component
@RequiredArgsConstructor
public class MessageSender {
    private final MessageChannels channels;

    public void notifyAdmin(String message) {
        channels.adminNotificationsOut().send(makeMessage(message));
    }

    private static Message makeMessage(String message) {
        return MessageBuilder.withPayload(new ExampleMessage(message)).build();
    }
}
```
</details>
<details>
  <summary>application.yml</summary>

```yml
spring:
  cloud.stream.bindings:
    admin-out:
      binder: rabbit
      contentType: application/json
      destination: notifications
    v2-admin-in: # why can't I use admin-in?
      binder: rabbit
      contentType: application/json
      destination: notifications

  cloud.stream.rabbit.bindings:
    admin-out:
      producer:
        routingKeyExpression: "'admin'"
    v2-admin-in: # I really don't get it
      consumer:
        bindingRoutingKey: admin

```
</details>

**Comment by lz101010** [comment]
Another issue that I've observed is the following:

If I add a second contract test that verifies messaging on an additional channel, then only one of the channels will end up with subscribers.
```
// run admin tests -> pass
 INFO 28027 --- [    Test worker] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'application.v2-admin-in' has 1 subscriber(s).
 INFO 28027 --- [    Test worker] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'application.admin-cin' has 0 subscriber(s).

// run clients tests -> fail
 INFO 28027 --- [    Test worker] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'application.v2-admin-in' has 1 subscriber(s).
ERROR 28027 --- [YmSV1ESUY1dHQ-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.clients-in'.
 INFO 28027 --- [    Test worker] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'application.admin-cin' has 0 subscriber(s).
```
This happens if I either run all contract tests at once or one-by-one. If I remove either channel along with the corresponding contract test, the remaining contract test passes.

I haven't added this second contract test to the repo, because I can't get both contract tests to pass and I'm not sure how to disable it by other means than not including it.
<details>
  <summary>Contract Test</summary>

  ```java
Contract.make {
label "notify clients"
    input {
        triggeredBy('notifyClients()')
    }

    outputMessage {
        sentTo("notifications")
        body([
                "message": "fizzbuzz"
        ])
    }
}
  ```
  </details>
</details>
<details>
  <summary>Messaging Components</summary>

```java
public interface MessageChannels {
    public static final String ADMIN_IN = "v2-admin-in";
    public static final String ADMIN_OUT = "admin-out";

    public static final String CLIENTS_IN = "clients-in";
    public static final String CLIENTS_OUT = "cllients-out";

    @Input(ADMIN_IN) 
    MessageChannel adminNotificationsIn();

    @Output(ADMIN_OUT) 
    MessageChannel adminNotificationsOut();

    @Input(CLIENTS_IN) 
    MessageChannel clientsNotificationsIn();

    @Output(CLIENTS_OUT) 
    MessageChannel clientsNotificationsOut();
}

@Component
@Slf4j
public class MessageReceiver {
    @StreamListener(MessageChannels.ADMIN_IN)
    public void receiveAdminNotification(ExampleMessage message) {
        log.info("Received admin notification: {}", message);
    }
    @StreamListener(MessageChannels.CLIENTS_IN)
    public void receiveClientsNotification(ExampleMessage message) {
        log.info("Received clients notification: {}", message);
    }
}

@Component
@RequiredArgsConstructor
public class MessageSender {
    private final MessageChannels channels;

    public void notifyAdmin(String message) {
        channels.adminNotificationsOut().send(makeMessage(message));
    }

    public void notifyClients(String message) {
        channels.clientsNotificationsOut().send(makeMessage(message));
    }

    private static Message makeMessage(String message) {
        return MessageBuilder.withPayload(new ExampleMessage(message)).build();
    }
}
```
</details>
<details>
  <summary>application.yml</summary>
```yml
spring:
  cloud.stream.bindings:
    admin-out:
      binder: rabbit
      contentType: application/json
      destination: notifications
    clients-out:
      binder: rabbit
      contentType: application/json
      destination: notifications
    admin-cin:
      binder: rabbit
      contentType: application/json
      destination: notifications
    clients-in:
      binder: rabbit
      contentType: application/json
      destination: notifications

  cloud.stream.rabbit.bindings:
    admin-out:
      producer:
        routingKeyExpression: "'admin'"
    clients-out:
      producer:
        routingKeyExpression: "'clients'"
    admin-cin:
      consumer:
        bindingRoutingKey: admin
    clients-in:
      consumer:
        bindingRoutingKey: clients
```
</details>
