### ISSUE TITLE
Regression in headers matchers from 3.0.2 to 3.0.3

### ISSUE THREAD

**Issue by razubuddy** [spring-cloud/spring-cloud-contract#1666]
I have such contract in YAML:
```
name: upload-file
request:
  method: POST
  url: /user/upload-file
  headers:
    Content-Type: multipart/form-data;boundary=AaB03x
  multipart:
    params:
      name: "fileName.md"
    named:
      - paramName: "file"
        fileName: "fileName.md"
        fileContent: "file content"
  matchers:
    headers:
      - key: Content-Type
        regex: "multipart/form\\-data.*"
    multipart:
      params:
        - key: name
          regex: ".+"
      named:
        - paramName: "file"
          fileName:
            predefined: non_empty
          fileContent:
            predefined: non_empty
response:
  status: 200
  body:
    fileName: "fileName.md"
```
After `generateClientStubs` in version 3.0.2 was:
```
    "headers" : {
      "Content-Type" : {
        "matches" : "multipart/form\\-data.*"
      },
    }
```
In 3.0.3 is:
```
    "headers" : {
      "Content-Type" : {
        "equalTo" : "multipart/form-data;boundary=AaB03x"
      },
    },
```
