### ISSUE TITLE
Provide possibility for custom WireMock RequestMatcherExtension

### ISSUE THREAD

**Issue by AlexanderTresenstein** [spring-cloud/spring-cloud-contract#1703]
**Is your feature request related to a problem? Please describe.**
I would like to provide a custom RequestMatcherExtension as defined by WireMock to cover special matching scenarios.

**Describe the solution you'd like**
The YAML DSL may look like this:
```yml
request:
...
  matchers:
    custom:
      - name: my-custom-matcher
        parameters:
          param1: value1
          param2: value2
      - name: my-other-custom-matcher
        parameters:
          paramA: valueA
          paramB: valueB
...
```

**Describe alternatives you've considered**
So far I found [this question](https://stackoverflow.com/a/45297717) with @marcingrzejszczak's answer. Though I have not tried it yet, I will see how far it gets me. Nevertheless I think this feature would help to improve the spring cloud contract experience.

**Additional context**
Maybe a custom RequestMatcherExtension could work as a work around to provide a fix for [this issue](https://github.com/spring-cloud/spring-cloud-contract/issues/716) which at the time was seen depending on this [WireMock issue](https://github.com/tomakehurst/wiremock/issues/398) which seems to be hard to fix, but has a workaround mentioned [here](https://github.com/tomakehurst/wiremock/issues/398#issuecomment-778465146).
