### ISSUE TITLE
Metadata duplication on stub mappings generation

### ISSUE THREAD

**Issue by gabbigum** [spring-cloud/spring-cloud-contract#1727]
**Describe the bug**

Hi, all. I have the following issue. When creating a contract with the wiremock webhook extension the generated stub mappings duplicate the **postServeActions**.

This contract:
```
request:
  method: POST
  url: /provision
  body:
    "machine": "aws-VM"
    "callbackURL": "http://localhost:8080/callback"
  headers:
    Content-Type: application/json
response:
  status: 200
metadata:
  wiremock:
    stubMapping:
      postServeActions:
        webhook:
          method: PATCH
          url: "http://localhost:8080/callback"
          headers:
            Content-Type: "application/json-patch+json"
          body: "{ \"host\" : \"AWS\" }"
```

Generates this stub mapping: 
```
{
  "id" : "3466c327-f926-4ecb-bad2-ae328516e0f4",
  "request" : {
    "urlPath" : "/provision",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "equalTo" : "application/json"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$[?(@.['machine'] == 'aws-VM')]"
    }, {
      "matchesJsonPath" : "$[?(@.['callbackURL'] == 'http://localhost:8080/callback')]"
    } ]
  },
  "response" : {
    "status" : 200
  },
  "uuid" : "3466c327-f926-4ecb-bad2-ae328516e0f4",
  "postServeActions" : [ {
    "name" : "webhook",
    "parameters" : {
      "method" : "PATCH",
      "url" : "http://localhost:8080/callback",
      "headers" : {
        "Content-Type" : "application/json-patch+json"
      },
      "body" : "{ \"host\" : \"AWS\" }"
    }
  }, {
    "name" : "webhook",
    "parameters" : {
      "method" : "PATCH",
      "url" : "http://localhost:8080/callback",
      "headers" : {
        "Content-Type" : "application/json-patch+json"
      },
      "body" : "{ \"host\" : \"AWS\" }"
    }
  } ]
}

```

Am I doing something wrong in my stubMapping definition or this is a valid bug? If it is a bug I would like to get some info which files to check/debug and help and fixing it.

Thanks in advance!
