### ISSUE TITLE
No consistent date format between the real application, contract tests and generated stub mappings

### ISSUE THREAD

**Issue by virgium03** [spring-cloud/spring-cloud-contract#1760]
Hello,

I'm using `Spring Boot 2.6.3` and `Spring Cloud Contract 3.1.0` and `Jackson 2.11.3` when writing contract ttests. This issue might be possibly related to the Maven plugin.

I am having troubles when dealing with `java.util.Date` objects when writing contract tests using your wonderful library.

First of all, I noticed that the default documented setup with`RestAssuredWebTestClient.standaloneSetup(controller)` does not use the `Jackson Object Mapper` of the application context. I was unpleasantly surprised to find out that the real application was generating `java.util.Date` objects using the `ISO 8601 offset` format (`2022-03-17T10:34:11.815+00:00`) but the application (context) used by the tests was generating the `date as timestamp` format (`1641551651813`). I would say that here, when dealing with dates, there is a big possibility of not being aligned with what the real application would produce. I did not test the behaviour with the new `Java 8` date time classes.

Please note that the real application has no additional `Jackson` or `JSON` configuration for `Spring Boot`.

I was able to overcome the issue by using something along the lines of manually injecting an `ObjectMapper`, creating an `HTTP message converter` and setting it on an instance of `MockMvc`. Maybe the documentation should stress more that the `MockMvc` configuration does not necessarily match the real one or give more details about how to configure it.

```java
@SpringBootTest(classes = {MyConfiguration.class, ActorsController.class})
@AutoConfigureJson
@AutoConfigureJsonTesters
public class BaseContractTestClass {

    @Autowired
    private ActorsController actorsController;

    @Autowired
    private ObjectMapper objectMapper;

    @BeforeEach
    public void setup() {        
        MappingJackson2HttpMessageConverter mappingJackson2HttpMessageConverter = new
                MappingJackson2HttpMessageConverter();
        mappingJackson2HttpMessageConverter.setObjectMapper(objectMapper);
        MockMvc mockMvc = MockMvcBuilders
                .standaloneSetup(actorsController)
                .setMessageConverters(mappingJackson2HttpMessageConverter)
                .build();
        RestAssuredMockMvc.mockMvc(mockMvc);
    }

}
````

In this way I was able to assert in a contract file that the date format matches a predefined format `iso_8601_with_offset` using dynamic body matchers in a `yml` file.

But then, when running the tests on the client consumer side, I noticed that the `JSON` which the client sees has the dates still in the `timestamp` format. I checked the generated stubs and their mappings and, indeed, the dates are not using the `iso_8601_with_offset` format. I don't understand why and I could not find where the problem comes from.

Once again, I would like to point out that there is no special `JSON` `Spring Boot` configuration in the application, just the default one, as far as I'm aware.

Any ideas why and how to get the dates in the same format, in the contract tests on the producer and the generated stubs used by the consumer?

Many thanks,
Virgiliu

**Comment by virgium03** [comment]
Jackson `jackson-datatype-jdk8` and `jackson-datatype-jsr310` are transitive dependencies from `spring-boot-starter-json`.

**Comment by marcingrzejszczak** [comment]
AFAIR the best way would be to pass the web application context via `RestAssuredMockMvc.webAppContextSetup`. That way things should be resolved from application context instead of passing them manually

**Comment by virgium03** [comment]
> AFAIR the best way would be to pass the web application context via `RestAssuredMockMvc.webAppContextSetup`. That way things should be resolved from application context instead of passing them manually

In the end, i simplified the base class like this:

```java
@WebMvcTest
@TestPropertySource("/application-test.properties")
@Import(xxx.class)
public class BaseContractTestClass {

    @Autowired
    private MockMvc mockMvc;

    @BeforeEach
    public void setup() {       
        RestAssuredMockMvc.mockMvc(mockMvc);
    }

}
```

But that was not the issue that I was referring to.

The problem is in the JSON stubs which are generated as a jar file for the clients, more precisely the JSON `response body` under the `mappings` folder. There the `java.util.Date` objects are serialized as timestamps, which is not consistent with the format used by the server (controllers), which is the `iso_8601_with_offset` format. From what I've seen, these are the responses that the client will get from the `Wiremock` server and they do not match the actual responses received by a client on the real server.

**Comment by marcingrzejszczak** [comment]
Can you show the contract, the generated test and the WireMock mapping?

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by virgium03** [comment]
Here is the contract file:

```yaml
name: search actors using criteria
request:
  method: GET
  url: /secure/v1.0/actors
  queryParameters:
    uuId: nsupuser

response:
  status: 200
  body:
    - id: 1
      uuId: nsupuser
      lastReactivationDate: 2022-01-07T10:34:11.813+00:00
      recUserId: hodor
      recDate: 2022-01-07T10:34:11.815+00:00
      modUserId: hodor
      modDate: 2022-03-10T13:45:44.097+00:00
  headers:
    Content-Type: application/json
  matchers:
    body:
      - path: $.[0].lastReactivationDate
        type: by_regex
        predefined: iso_8601_with_offset
      - path: $.[0].recDate
        type: by_regex
        predefined: iso_8601_with_offset
      - path: $.[0].modDate
        type: by_regex
        predefined: iso_8601_with_offset
```
