### ISSUE TITLE
spring-cloud-contract docker images with version 3.x.x do not publish

### ISSUE THREAD

**Issue by johnathana** [spring-cloud/spring-cloud-contract#1784]
Using docker image `springcloud/spring-cloud-contract` with version 3+ does not publish on maven, printing in the logs 
`> Task :publish UP-TO-DATE
`

**Sample**
Run the attached [docker-compose](https://github.com/spring-cloud/spring-cloud-contract/files/8702550/issue.zip) env with:
`TAG=3.1.2 docker-compose up`
[stub artifact](http://localhost:8081/artifactory/libs-release-local/com/example/example/0.0.1.RELEASE/example-0.0.1.RELEASE-stubs.jar) is not uploaded to artifactory.

`TAG=2.2.8.RELEASE docker-compose up`
[stub artifact](http://localhost:8081/artifactory/libs-release-local/com/example/example/0.0.1.RELEASE/example-0.0.1.RELEASE-stubs.jar) is uploaded.

**Comment by marcingrzejszczak** [comment]
We have a sample that tests this https://github.com/spring-cloud-samples/spring-cloud-contract-nodejs can you double check what the difference is between yours and this sample?

**Comment by johnathana** [comment]
Sorry this project does not work for me either and I cannot narrow down the use case more than the already provided docker-compose.

**Comment by manuporto** [comment]
Hi, I'm having a similar problem. The sample project does not work for me as well, it does not publish anything at all. The tag being used is `3.1.1`.

**Comment by marcingrzejszczak** [comment]
The problem was that with 3.0.0 (so that's a pretty long regression) that we have disabled the default maven publication that was added to the Gradle build. With this commit I'm adding it back together with 3 additional environment variables

* `DEBUG` to add debug option to the Gradle build within the Docker build
* `ADDITIONAL_FLAGS`  additional flags added to the Gradle build
* `REPO_ALLOW_INSECURE_PROTOCOL` to allow publication to Artifact Managers under `http`

So your docker-compose (thanks for the sample it was super useful) would look like this

```yaml
version: "2"
services:
  artifactory:
    build:
      context: .
      dockerfile: Dockerfile-artifactory
    ports:
      - "8081:8081"
  contract:
    image: "springcloud/spring-cloud-contract:${TAG}"
    depends_on:
      - artifactory
    environment:
      - APPLICATION_BASE_URL=http://jsonplaceholder.typicode.com
      - PUBLISH_ARTIFACTS=true
      - REPO_WITH_BINARIES_URL=http://artifactory:8081/artifactory/libs-release-local
      - PROJECT_GROUP=com.example
      - PROJECT_NAME=example
      - PROJECT_VERSION=0.0.1.RELEASE
      - REPO_ALLOW_INSECURE_PROTOCOL=true
    volumes:
      - ./contracts:/contracts
```
