### ISSUE TITLE
Priority property not transfer when convert contract to yaml

### ISSUE THREAD

**Issue by arseniqueee** [spring-cloud/spring-cloud-contract#1796]
Hello, everyone!

I have an issue while test spring-cloud-contract-maven-plugin. My contracts develop with Groovy DSL. I want convert them in yaml format. I enabled plugin configuration property <convertToYaml> and contracts converted successfully. But, my contracts have priority property, which use for consumers stubs ordering. In converted yamls priority alway null. I think i can fix this with adding one line of code. Can you see my solution? 

Example Groovy DSL contract:
```
Contract.make {
            priority (1)
            name "Account creating without sign"
            request {
                method POST()
                urlPath("/account")
                headers {
                    contentType(applicationJson())
                    header("userId", anyNonBlankString())
                    header("sign", "")
                }
                body(
                        "number": anyNonBlankString(),
                        "currency": "USD",
                        "owner": "owner"
                )
            }
            response {
                status CREATED()
                headers {
                    contentType(applicationJson())
                }
                body(
                        "id": anyNonBlankString(),
                        "number": "number",,
                        "currency": "USD",
                        "owner": "owner",
                        "balance": 0
                )
            }
        }
```

Example converted YAML without fix:
```
---
request:
  method: "POST"
  url: null
  urlPath: "/account"
  queryParameters: {}
  headers:
    Content-Type: "application/json"
    userId: "YYVWTCKCNHHKFGTTVTPF"
    sign: ""
  cookies: null
  body:
    number: "ZGQRIZASKJHEWFMRFOHQ"
    currency: "USD"
    owner: "owner"
  bodyFromFile: null
  bodyFromFileAsBytes: null
  matchers:
    url: null
    body:
    - path: "$.['number']"
      type: "by_regex"
      value: "^\\s*\\S[\\S\\s]*"
      predefined: null
      minOccurrence: null
      maxOccurrence: null
      regexType: "as_string"
    headers:
    - key: "Content-Type"
      regex: "application/json.*"
      predefined: null
      command: null
      regexType: "as_string"
    - key: "userId"
      regex: "^\\s*\\S[\\S\\s]*"
      predefined: null
      command: null
      regexType: "as_string"
    queryParameters: []
    cookies: []
    multipart: null
  multipart: null
response:
  status: 201
  headers:
    Content-Type: "application/json"
  cookies: null
  body:
    id: "FNSNPZHDYTJGUQZVZESN"
    number: "number"
    currency: "USD"
    owner: "owner"
    balance: 0
  bodyFromFile: null
  bodyFromFileAsBytes: null
  matchers:
    body:
    - path: "$.['id']"
      type: "by_regex"
      value: "^\\s*\\S[\\S\\s]*"
      minOccurrence: null
      maxOccurrence: null
      predefined: null
      regexType: "as_string"
    headers:
    - key: "Content-Type"
      regex: "application/json.*"
      command: null
      predefined: null
      regexType: "as_string"
    cookies: []
  async: false
  fixedDelayMilliseconds: null
input: null
outputMessage: null
description: null
label: null
name: "Account creating without sign"
priority: null
ignored: false
inProgress: false
metadata: {}

```

Example converted YAML with my fix:

```
---
request:
  method: "POST"
  url: null
  urlPath: "/account"
  queryParameters: {}
  headers:
    Content-Type: "application/json"
    userId: "YYVWTCKCNHHKFGTTVTPF"
    sign: ""
  cookies: null
  body:
    number: "ZGQRIZASKJHEWFMRFOHQ"
    currency: "USD"
    owner: "owner"
  bodyFromFile: null
  bodyFromFileAsBytes: null
  matchers:
    url: null
    body:
    - path: "$.['number']"
      type: "by_regex"
      value: "^\\s*\\S[\\S\\s]*"
      predefined: null
      minOccurrence: null
      maxOccurrence: null
      regexType: "as_string"
    headers:
    - key: "Content-Type"
      regex: "application/json.*"
      predefined: null
      command: null
      regexType: "as_string"
    - key: "userId"
      regex: "^\\s*\\S[\\S\\s]*"
      predefined: null
      command: null
      regexType: "as_string"
    queryParameters: []
    cookies: []
    multipart: null
  multipart: null
response:
  status: 201
  headers:
    Content-Type: "application/json"
  cookies: null
  body:
    id: "FNSNPZHDYTJGUQZVZESN"
    number: "number"
    currency: "USD"
    owner: "owner"
    balance: 0
  bodyFromFile: null
  bodyFromFileAsBytes: null
  matchers:
    body:
    - path: "$.['id']"
      type: "by_regex"
      value: "^\\s*\\S[\\S\\s]*"
      minOccurrence: null
      maxOccurrence: null
      predefined: null
      regexType: "as_string"
    headers:
    - key: "Content-Type"
      regex: "application/json.*"
      command: null
      predefined: null
      regexType: "as_string"
    cookies: []
  async: false
  fixedDelayMilliseconds: null
input: null
outputMessage: null
description: null
label: null
name: "Account creating without sign"
priority: 1
ignored: false
inProgress: false
metadata: {}
```

But i cant push my fix :( i have 403, and i don't know why.

Thanks for your response! And sorry for my bad english :)
