### ISSUE TITLE
EurekaServiceDiscovery name should be taken from application.yml not gradle.properties

### ISSUE THREAD

**Issue by yacekmm** [spring-cloud/spring-cloud-contract#180]
Service name in Eureka is taken from property `spring.application.name`. Whereas SCC regsters its stub runner in Eureka under the name taken from gradle properties `serviceName`

Can you fix it? 

Right now the workaround is to use `stubrunner.idsToServiceIds: <serviceName>: <spring.application.name>`

**Comment by marcingrzejszczak** [comment]
Wait I don't follow...

We're on the client side. Your client app has a configuration

```
spring.application.name: foo
stubrunner:
  ids: com.acme:security.service:1.0.0:stubs
  idsToServiceIds:
    security.service: securityService
```

Now how can Stub Runner register the stub (`sercurity.service`) with the `spring.application.name` of the consumer? That makes no sense. But most likely I'm not following sth...
