### ISSUE TITLE
Dockerized provider verifier with MQTT - Message is null

### ISSUE THREAD

**Issue by lukaszmalekharman** [spring-cloud/spring-cloud-contract#1892]
I Configured dockerized  spring verifier, to verify provider that produces mqtt message. Message is being created and published on the locally working broker (mosquitto), the test case is generated, but when running test - message is null. I think i checked every option that came to me and didn't found the solution. Could anybody advice me on this?

Here is the contract:
```
description: Send a pong message in response to a ping message
label: standalone_ping_pong
input:
  triggeredBy: triggerMessage("ping_pong")
outputMessage:
  sentTo: paho:example_topic
  body:
    message: pong
metadata:
  standalone:
    setup:
      endpoint:
        uri: paho:topic?brokerUrl=tcp://host.docker.internal:1883&clientId=my-client
        type: paho
        options:
          clientId: my-client
    outputMessage:
      additionalOptions: brokerUrl=tcp://localhost:1883
```

Here is generated test case:

```
@Test
public void validate_pingPongStandalone() throws Exception {
	// when:
		triggerMessage("ping_pong");

	// then:
		ContractVerifierMessage response = contractVerifierMessaging.receive("paho:example_topic",
				contract(this, "pingPongStandalone.yml"));
		assertThat(response).isNotNull();

	// and:;

	// and:
		DocumentContext parsedJson = JsonPath.parse(contractVerifierObjectMapper.writeValueAsString(response.getPayload()));
			assertThatJson(parsedJson).field("['message']").isEqualTo("pong");
	}
```

Here is the docker run command i use:

```
docker run  --rm \
                --name verifier \
                --network host \
                -e "STANDALONE_PROTOCOL=paho" \
                -e "CAMEL_COMPONENT_PAHO_SERVER-U-R-IS=tcp://host.docker.internal:1883" \
                -e "PUBLISH_STUBS_TO_SCM=false" \
                -e "PUBLISH_ARTIFACTS=false" \
                -e "APPLICATION_BASE_URL=${APPLICATION_BASE_URL}" \
                -e "PROJECT_NAME=${PROJECT_NAME}" \
                -e "PROJECT_GROUP=${PROJECT_GROUP}" \
                -e "PROJECT_VERSION=${PROJECT_VERSION}" \
                -e "EXTERNAL_CONTRACTS_REPO_WITH_BINARIES_URL=git://https://github.com/example/scc_python_contracts.git" \
                -e "EXTERNAL_CONTRACTS_ARTIFACT_ID=${PROJECT_NAME}" \
                -e "EXTERNAL_CONTRACTS_GROUP_ID=${PROJECT_GROUP}" \
                -e "EXTERNAL_CONTRACTS_VERSION=${PROJECT_VERSION}" \
                -v "${CURRENT_DIR}/build/spring-cloud-contract/output:/spring-cloud-contract-output/" \
                springcloud/spring-cloud-contract:"${SC_CONTRACT_DOCKER_VERSION}"
```

Here is error message:
```
MessagingTest > validate_pingPongStandalone() FAILED
    java.lang.AssertionError: 
    Expecting actual not to be null
        at contracts.consumer1.MessagingTest.validate_pingPongStandalone(MessagingTest.java:32)
```

Would greatly appreciate any help
