### ISSUE TITLE
ContractVerifierUtil can not find referenced resources

### ISSUE THREAD

**Issue by raynigon** [spring-cloud/spring-cloud-contract#1919]
**Describe the bug**
Since version 4.0.3 referenced files are no longer found by the `ContractVerifierUtil`. 
The `fileToBytes` function throws a `FileNotFoundException` because the class loader is no longer able to find the referenced files.

**Kotlin:** 1.9
**JDK Version:** Java_Adopt_jdk 17.0.7-7 x64
**Gradle Version:** 7.6

**Sample**
Contract:

```yaml
name: Upload minimal GPX File
request:
  url: /api/routes/import/gpx
  method: POST
  headers:
    Content-Type: application/xml
  bodyFromFileAsBytes: "minimal.gpx"
response:
  status: 201
  headers:
    Content-Type: application/json
  body:
    id: "4073c594-58ce-4468-a1ed-af06455c71c4"
    version: 0
    title: "GPX file import"
    updatedDate: "2020-02-14T15:42:24.123+0000"
    state: "CREATED"
```

The `minimal.gpx` is placed next to the contract in the same directory.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx
    version="1.1"
    creator="Runkeeper - http://www.runkeeper.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.topografix.com/GPX/1/1"
    xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"
    xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1">
    <wpt lat="37.778259000" lon="-122.391386000"><ele>3.4</ele><time>2016-06-17T23:41:03Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
    <wpt lat="37.778194000" lon="-122.391226000"><ele>3.4</ele><time>2016-06-17T23:41:13Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
    <wpt lat="37.778297000" lon="-122.391174000"><ele>3.4</ele><time>2016-06-17T23:41:18Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
    <wpt lat="37.778378000" lon="-122.391117000"><ele>3.4</ele><time>2016-06-17T23:41:23Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
    <wpt lat="37.778449000" lon="-122.391039000"><ele>3.4</ele><time>2016-06-17T23:41:26Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
    <wpt lat="37.778525000" lon="-122.390942000"><ele>3.4</ele><time>2016-06-17T23:41:29Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
</gpx>
```
