### ISSUE TITLE
Spring Cloud Contract Fails to generate tests for Form URL encoded request body

### ISSUE THREAD

**Issue by DhavalShewale** [spring-cloud/spring-cloud-contract#1931]
Spring Cloud Contract does not generate correct test classes for Form URL encoded request body

**Version:** `4.0.4`

## Contract
``` yaml
request:
  method: POST
  url: /exportData
  body: "fromDt=16-Aug-2023&toDt=25-Aug-2023"
  headers:
    Content-Type: "application/x-www-form-urlencoded; charset=UTF-8"
response:
  status: 200
  bodyFromFileAsBytes: response/export_data.xlsx
  headers:
    Content-Disposition: "attachment; filename=[EXTRACT] Export Data.xlsx"
```

## Generated Test Case
``` java
@Test
public void validate_export_data() throws Exception {
	// given:
		MockMvcRequestSpecification request = given()
				.header("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8")
				.body("");

	// when:
		ResponseOptions response = given().spec(request)

				.post("/exportData");

	// then:
		assertThat(response.statusCode()).isEqualTo(200);
		assertThat(response.header("Content-Disposition")).isEqualTo("attachment; filename=[EXTRACT] Export Data.xlsx");


	// and:
		assertThat(response.getBody().asByteArray()).isEqualTo(fileToBytes(this, "export_data_response_export_data.xlsx"));
}
```

The body of request is generated as empty string in Test Class instead of the configured body in yaml

The behavior is same even if contract is configured in groovy as follows:

``` groovy

org.springframework.cloud.contract.spec.Contract.make {
  request {
    method 'POST'
    url '/exportData'
    headers {
      header("Content-Type": 'application/x-www-form-urlencoded; charset=UTF-8')
    }
    body('fromDt=16-Aug-2023&toDt=25-Aug-2023')
  }
  response {
    status 200
  }
}

```
