### ISSUE TITLE
Unable to download stubs from repository via HTTPS

### ISSUE THREAD

**Issue by tommysitu** [spring-cloud/spring-cloud-contract#195]
With version 1.0.3-RELEASE, I am using the following stubrunner configuration in my Spring Boot application profile: 

```
stubrunner:
  ids: io.specto:test-svc:+:stubs:8080
  repositoryRoot: https://test.jfrog.io/specto/libs-snapshot-local
  username: ${ARTIFACTORY_USERNAME}
  password: ${ARTIFACTORY_PASSWORD}
```

When I run my test, I am getting the following exception:
```
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.specto:test-svc:jar:stubs:1.0-SNAPSHOT from/to remote0 (http://test.jfrog.io/specto/libs-snapshot-local): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

The test would pass if I have workOffline turned on.  

I think the issue is to do with missing SSL certificate.
