### ISSUE TITLE
Properties wiremock.server.* aren't kept when configuring Options

### ISSUE THREAD

**Issue by alexisgayte** [spring-cloud/spring-cloud-contract#2136]
Describe the bug

It seems that the change provided in this https://github.com/spring-cloud/spring-cloud-contract/issues/1920 led to undesired behaviour by defaulting the server port always to 8080 after setting.

The wiremock.server.port property even if it has been already set will be overidden.
If some option are set : 
for example : 
```
@AutoConfigureWireMock
@Configuration
public class WiremockConfig {

    @Bean
    public Options wireMockOptions() {
        return WireMockSpring.options()
                .notifier(new Slf4jNotifier(true));
    }
}
```

```
wiremock:
  server:
    files: classpath:/__files
    stubs: classpath:/mappings
    port: 8082

```

Thanks in Advance
