### ISSUE TITLE
body in contract doesn't seem to accept an array of objects

### ISSUE THREAD

**Issue by quiram** [spring-cloud/spring-cloud-contract#621]
I'm trying to write a contract for a REST service that will return a JSON Array in the body, something like this:

```
GET <server>/products

[{"id": "1", "productName": "car"}, {"id":"2", "productName": "motorbike"}]
```

Which in the `yaml` form of the contract I'm trying to type as:

```
request:
  method: GET
  url: /products
response:
  status: 200
  body:
    - id: 1
      productName: car
    - id: 2
      productName: motorbike
```

But when I try I get the following error:

```
 No signature of method: org.springframework.cloud.contract.spec.internal.Body$_closure3.doCall() is applicable for argument types: (java.util.LinkedHashMap) values: [[id:1, productName:car]]
```

Oddly enough, the second element isn't mentioned in the error, only the first one.

spring-cloud-dependencies version: Camden.SR7
spring-cloud-contract version: 1.2.4.RELEASE

Please let me know if I can provide any other information to help. Thanks!
