### ISSUE TITLE
AutoConfigureStubRunner doesn't work with Ribbon listOfServers configuration

### ISSUE THREAD

**Issue by jrobison153** [spring-cloud/spring-cloud-contract#699]
Hi,

I'm having an issue with stub runner since upgrading from Edgware to Finchley. It appears as if the enabling AutoConfigureStubRunner clears out any other Ribbon configuration, attempts to use my Feign client results in the following error:

`Load balancer does not have available server for client: cool-service`

Here's how to reproduce the issue

mock profile for configuring ribbon for use by a feign client
```
cool-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:${local.server.port}

stubrunner:
  idsToServiceIds:
    nifty-spec: "nifty-service"
  ids: "com.foo:nifty-spec"

eureka:
  client:
    enabled: true
    register-with-eureka: false
    fetch-registry: false

feign:
  hystrix:
    enabled: false

```
Test code

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles({ "mock" })
@EnableFeignClients(clients = { GreetingApiClient.class })
@DirtiesContext
@AutoConfigureStubRunner
@RunWith(SpringRunner.class)
public class StubRunnerIssue {

	@Autowired
	private CoolApiClient client;

	@Test
	public void stubRunnerIssueExample() {

		this.client.getCool();
	}
}

```

Feign client and service interface/implementation

```
@FeignClient(name="cool-service", configuration = CoolClientConfiguration.class)
public interface CoolServiceApiClient extends CoolApi {
}

public interface CoolApi {

    @RequestMapping(value = "/cool",
        produces = "application/json",
        consumes = "",
        method = RequestMethod.GET)
    ResponseEntity<CoolResponse> getCool();

}

@RestController
public class CoolController implements CoolApi {

	@Autowired
	private NiftyClient niftyClient;

	@Override
	public ResponseEntity<CoolResponse> getCool() {

		try {
		
		    // call service that should be stubbed by stub runner
			ResponseEntity<NiftyResponse> niftyResponse = this.niftyClient.getSomethingNifty();
		}
		catch (NullPointerException e) {
			throw e;
		}
		return ResponseEntity.ok();
	}
}
```
In the unit test code, if you remove `@AutoConfigureStubRunner` then ribbon is able to find the configured server and the rest service is called, the test will eventually fail because the service then tries to call the client that was supposed to be stubbed out by the stub runner, but we disabled it.

Please note that this configuration worked in the Edgware release train, but since upgrading to Finchley.RELEASE this problem presents.
