### ISSUE TITLE
NullPointerException at org.springframework.cloud.contract.verifier.assertion.CollectionAssert.allElementsMatch

### ISSUE THREAD

**Issue by srs-haw** [spring-cloud/spring-cloud-contract#703]
I wrote a yaml-contract with the following body-matcher:
```yaml
    - path: $..email
      type: by_regex
      predefined: email
```
The following code is being generated by `./gradlew generateContractTests` for validation on the producer side:
```java
assertThat((java.lang.Iterable) parsedJson.read("$..email", java.util.Collection.class))
.as("$..email").allElementsMatch("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}");
```
This leads to an exception while executing the above line:
```java
java.lang.NullPointerException at 
org.springframework.cloud.contract.verifier.assertion.CollectionAssert
.allElementsMatch(CollectionAssert.java:33)
```
The same problem arises when directly using a regular expression like
```yaml
    - path: $..email
      type: by_regex
      value: '[a-zA-Z0-9]+\.[a-zA-Z0-9]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}'
```
I am using Spring Cloud Contract Version 2.0.1.RELEASE - same problem with 2.0.2.SNAPSHOT.

**Comment by marcingrzejszczak** [comment]
Can you debug that and verify what is the value of `this.actual` in `CollectionAssert`? It looks as if it contained a list of nulls. Is that possible?

**Comment by srs-haw** [comment]
Hi Marcin, you're absolutely right :-( ...just didn't see that I have a json-object with a null-email in my result-list...probably I don't get the matching in this case right.
In my yaml I wrote
```yaml
response:
  status: 200
  body: '[{"id":null,"firstName":"Hui","lastName":"Boo","gender":"UNKOWN","email":
"hui.boo@ghosts.com"}]'
  matchers:
    headers:
    - key: Content-Type
      regex: "application/json.*"
    body:
    - path: $..email
      type: by_regex
      predefined: email
```
but my `baseClassForTests` inserts some more data - and one without an email...
