### ISSUE TITLE
Dynamic properties in messageHeaders-section

### ISSUE THREAD

**Issue by srs-haw** [spring-cloud/spring-cloud-contract#709]
I'd like to propose an enhancement.
I have to use manual acknowledgement of messages in a Spring Cloud Stream scenario like this:
```java
@StreamListener(MessagingChannelsChannelNames.INPUT)
    public void handle(@Payload int i,
                       @Header(AmqpHeaders.CHANNEL) Channel channel,
                       @Header(AmqpHeaders.DELIVERY_TAG) Long deliveryTag) throws IOException {
        // call some service-operations
        // ... and finally:
        channel.basicAck(deliveryTag, false);
    }
```
Therefore I have to pass a (mock)-Channel instance in my tests - by setting the message headers accordingly. For my own unit tests, this is not an issue.

Unfortunately I didn't find a way to do this in Spring Cloud Contract tests. A solution would be to allow dynamic properties in the messageHeaders-section like in this example this: 
```yaml
description: some description
label: accepted_verification2
input:
  messageFrom: eventsBookingserviceIn
  messageBody:
    "11"
  messageHeaders:
    amqp_channel: getMockChannel()  <---!!
    amqp_deliveryTag: 1
outputMessage:
    ...
```
getMockChannel() would a be function in my message test base class that just returns a mock(Channel.class) instance.
But in Spring Cloud Contract this currently gets compiled to:
```java
public void validate_testMessagingIn() throws Exception {
		// given:
			ContractVerifierMessage inputMessage = contractVerifierMessaging.create(
				"11"
				, headers()
					.header("amqp_channel", "getMockChannel()") <---!! wrong
					.header("amqp_deliveryTag", "1")
			);

		// when:
                ...
	}
```
