### ISSUE TITLE
Matchers section is missed in ContractVerifierTest

### ISSUE THREAD

**Issue by Hronom** [spring-cloud/spring-cloud-contract#722]
I'm use `2.0.1.RELEASE`.

I have response body
```
[
  {
    "id": "00000bb0b000b00000b0b000",
    "name": "Admin test project 1"
  },
  {
    "id": "11111bb1b111b11111b1b111",
    "name": "Admin test project 2"
  }
]
```

My contract in `yaml`
```
request:
  method: GET
  url: /projects
  headers:
    Content-Type: application/json;charset=UTF-8
response:
  status: 200
  headers:
    Content-Type: application/json;charset=UTF-8
  matchers:
    body:
      - path: $[0].id
        type: by_regex
        value: "[0-9a-z]{24}"
      - path: $[1].id
        type: by_regex
        value: "[0-9a-z]{24}"
```

The generated `ContractVerifierTest` don't has `matchers` part
```
        // given:
            MockMvcRequestSpecification request = given()
                    .header("Content-Type", "application/json;charset=UTF-8");

        // when:
            ResponseOptions response = given().spec(request)
                    .get("/projects");

        // then:
            assertThat(response.statusCode()).isEqualTo(200);
            assertThat(response.header("Content-Type")).isEqualTo("application/json;charset=UTF-8");
```

It will be good if `matchers` section will be generated even if no `body` section, since in this situation I have anonymous array with dynamic data that can't be verified in `body` section.

**Comment by marcingrzejszczak** [comment]
Nope, body is mandatory. There's no reason why you shouldn't provide the response body when you require matchers for it

**Comment by Hronom** [comment]
@marcingrzejszczak Ok, please can you recommend what to put in the `body` section for described response body?

**Comment by marcingrzejszczak** [comment]
```
[
  {
    "id": "00000bb0b000b00000b0b000",
    "name": "Admin test project 1"
  },
  {
    "id": "11111bb1b111b11111b1b111",
    "name": "Admin test project 2"
  }
]
```

**Comment by Hronom** [comment]
This trough file or there way to specify it in `yaml` directly?

Also id's here is dynamic, name is static, I run service with full context initialization.

**Comment by marcingrzejszczak** [comment]
Have you read the docs? https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#spring-cloud-contract-verifier-intro-three-minute-tour-producer

Id will be dynamic for test side, not the stub side?

**Comment by Hronom** [comment]
> Have you read the docs? https://cloud.spring.io/spring-cloud-static/Finchley.SR1/single/spring-cloud.html#spring-cloud-contract-verifier-intro-three-minute-tour-producer
Yes I have read that part and it's not cover my situation with anonymous array.
I still not understand how to add my static names in `body` section from two entities(since I have array).

This contract does not generate the java file:
(By the way no errors was throung during running of spring-cloud-contract:generateTests)
```
request:
  method: GET
  url: /projects
  headers:
    Content-Type: application/json;charset=UTF-8
response:
  status: 200
  headers:
    Content-Type: application/json;charset=UTF-8
  body:
    - "name": "Admin test project 1"
    - "name": "Admin test project 2"
  matchers:
    body:
      - path: $[0].id
        type: by_regex
        value: "[0-9a-z]{24}"
      - path: $[0].userId
        type: by_regex
        value: "[0-9a-z]{24}"
      - path: $[1].id
        type: by_regex
        value: "[0-9a-z]{24}"
      - path: $[1].userId
        type: by_regex
        value: "[0-9a-z]{24}"
```

> Id will be dynamic for test side, not the stub side?
Id will be dynamic on the producer side, also possibly consumer will put some dynamic id's too.
