### ISSUE TITLE
Error in code generation für json-array in yaml-contract

### ISSUE THREAD

**Issue by srs-haw** [spring-cloud/spring-cloud-contract#727]
I wrote a service contract for a REST-endpoint returning a list of bookings like this:
```yaml
description: test

request:
  method: GET
  urlPath: /v1/bookings
response:
  status: 200
  body: '[{"id": 1,"bookingId": 1,"bookingStatus": "ACCEPTED","checkinStatus": "PRE_CHECKIN"}]'
  headers:
    Content-Type: application/json;charset=UTF-8
  matchers:
    body:
    - path: $..id
      type: by_regex
      predefined: number
```

When generating the contract tests for the producer-side (```./gradlew generateContractTests```), the following code gets generated:
```java
public void validate_test() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();

		// when:
			ResponseOptions response = given().spec(request)
					.get("/v1/bookings");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);
			assertThat(response.header("Content-Type")).isEqualTo("application/json;charset=UTF-8");
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).array().isEmpty();
		// and:
			assertThat((java.lang.Iterable) parsedJson.read("$..id", java.util.Collection.class)).as("$..id").allElementsMatch("-?(\\d*\\.\\d+|\\d+)");
```
The generated line ```assertThatJson(parsedJson).array().isEmpty();``` must be false, since the service should return something, which is going to be checked afterwards by the matchers.
