### ISSUE TITLE
Need feature to mark API deprecated or forbidden

### ISSUE THREAD

**Issue by Hronom** [spring-cloud/spring-cloud-contract#746]
This provides a possibility for developers of producers to enforce/notify in automated way all developers of consumers to switch to the new version of the API.

Need two parameters:
1. `deprecated: true` - during test will print to the console warning on the consumer side
2. `forbidden: true` - breaks tests on the consumer side

Think about it is a high level parameters on the same level as `name` and `description`, example of `yaml` file:
```
name: some name
description: Some description
deprecated: true
request:
  url: /v1/foo
  body:
    foo: bar
response:
  status: 200
  headers:
    foo2: bar
    foo3: foo33
    fooRes: baz
  body:
    foo2: bar
    foo3: baz
    nullValue: null
```

With this feature, possible next workflow:
1. Add versioning to the internal API, lets say `/v1/user`.
2. After some time, create new API `/v2/users`
3. Mark old contracts(for old API `/v1/users`) as `forbidden: true`
4. Push new version of the user service in prod with `/v2/user` and `/v1/user` to the `master` and let it push stubs also to the `latest` version folder in git
5. During night scheduled running of tests, devs from other teams will see that there new API, since tests will fail because `latest` producer contract is changed
6. They will start transition to the new API

The flag `forbidden: true` needed because if you remove contracts for old version, on producer side you will not be able to validate your old API(since during transition it can be in use)
