### ISSUE TITLE
How to write contract with a json body with a string accepting multiple lines of text ?

### ISSUE THREAD

**Issue by benoitheinrich** [spring-cloud/spring-cloud-contract#802]
**Question**

I'm using the following versions:
- spring-boot 2.1.0.RELEASE
- spring-cloud-contract 2.0.2.RELEASE
- jackson 2.9.7

I'd like to define a contract where the request accepts a json body with a string accepting multiple lines of text:

```
request:
  url: /pendingFiles/submit
  queryParameters:
    username: John
  method: POST
  headers:
    Content-Type: application/json
  body:
    comment: |-
      Lorem Ipsum is simply dummy text of the printing and typesetting industry.
      Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...

response:
  status: 202
  body:
    status: success
    message: The new configuration is being applied
    username: John
    comment: |-
      Lorem Ipsum is simply dummy text of the printing and typesetting industry.
      Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...
```

Is this the way to create that contract, using simply a multiline text in my field (here comment field) ?

If so then there might be an issue with the generated test as it currently produces: 
```
	@Test
	public void validate_test() throws Exception {
		// given:
			RequestSpecification request = given()
					.header("Content-Type", "application/json")
					.body("{\"comment\":\"Lorem Ipsum is simply dummy text of the printing and typesetting industry.\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s...\"}");

		// when:
			Response response = given().spec(request)
					.queryParam("username","John")
					.post("/pendingFiles/submit");

		// then:
			assertThat(response.statusCode()).isEqualTo(202);
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['message']").isEqualTo("The new configuration is being applied");
			assertThatJson(parsedJson).field("['username']").isEqualTo("John");
			assertThatJson(parsedJson).field("['comment']").isEqualTo("Lorem Ipsum is simply dummy text of the printing and typesetting industry.\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s...");
			assertThatJson(parsedJson).field("['status']").isEqualTo("success");
	}
```

The problem is with the body where the json contains unquoted character (`\n`) and when this goes through jackson for parsing it generates the following error: 
```
nested exception is com.fasterxml.jackson.databind.JsonMappingException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (PushbackInputStream); line: 1, column: 12] (through reference chain: com.stuff.MyClass["comment"])
```
Notice that if I modify this test to properly escape the `\n` (to `\\n`) for the request part, then the test works.

I can workaround this for now by not using the multiline string in my yaml but then it's kind of less practical:
```
  body:
    comment: Lorem Ipsum is simply dummy text of the printing and typesetting industry.\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s...
```

Thanks again for your help.
