### ISSUE TITLE
How to validate array count for request in spring cloud contract

### ISSUE THREAD

**Issue by KanikaDeka** [spring-cloud/spring-cloud-contract#824]
I am trying to check array count in my contract for request using maxOccurance and minOccurance. My array count should not be greater than 2. But it is not happening. My contract looks like:

`name: Validating A CWP MO For New Customer Negative1
priority: 1
request:
  method: POST
  url: /ValidateMO
  bodyFromFile: cwp_mo_negative1.json
  headers:
    Content-Type: application/json
  matchers:
    body:
      - path: $.orderItem
        type: by_type
        minOccurrence: 1
      - path: $.orderItem
        type: by_type
        maxOccurrence: 2
response:
  status: 400
  body:  # (9)
    "status": "Order Item length should not be more than 2"
  headers: # (10)
    Content-Type: application/json;charset=UTF-8`

Can we use minOccurance and maxOccurance for request or is there any other way to do the same?

**Comment by marcingrzejszczak** [comment]
You can't do it for the request side. Why would you even want to do that? If there's supposed to be one entry only, then use a map instead. What is your use case?

**Comment by KanikaDeka** [comment]
In our case, we want to define a contract where it should pass for only specific number of Products.
e.g. In our json we should send only five products (not more or less than 5), so our contract should throw error if product count is not 5.

**Comment by marcingrzejszczak** [comment]
I see. Try with the jsonpath I provided as a workaround. I'll try to add a feature for this.

**Comment by KanikaDeka** [comment]
> Actually I was wrong. Can you try this: Let's say that you have an array called `things`
> 
> `$[?(@.things.size() == 2)]`

then for this path what will be type and value in my contract?

**Comment by marcingrzejszczak** [comment]
Can you paste your contract? and a sample request?

**Comment by KanikaDeka** [comment]
> Can you paste your contract? and a sample request?

Yes sure. cwp_mo.json is :
`{
  "version": 1,
  "systemId": "CPO",
  "externalId": "{externalId}",
  "orderSpecificationCode": "CPO",
  "orderCharacteristic": [
    {
      "value": "{orderCreationDate}",
      "name": "orderCreationDate"
    },
    {
      "value": "{Project_Manager_Required}",
      "name": "Project_Manager_Required"
    },
    {
      "value": "{Project_ID}",
      "name": "Project_ID"
    },
    {
      "value": "{orderComplexity}",
      "name": "orderComplexity"
    }
  ],
  "orderItem": [
    {
      "id": "{orederItemId}",
      "product": {
        "id": "{productId}",
        "action": "add",
        "productSpecification": {"code": "000028"},
        "productCharacteristic": [
          {
            "name": "CustomerPreferredName",
            "value": ""
          },
          {
            "name": "MulticastEnabled",
            "value": "FALSE"
          }
        ]
      }
    },
    {
      "id": "{orederItemId}",
      "product": {
        "id": "{productId}",
        "action": "add",
        "productSpecification": {"code": "000027"}
      }
    }
  ]
}`

Contract:

`name: Validating A CWP MO For New Customer
priority: 2
request:
  method: POST
  url: /ValidateMO
  bodyFromFile: cwp_mo.json
  headers:
    Content-Type: application/json
  matchers:
    body:
      - path: $.externalId
        type: by_regex
        value: "[A-Za-z0-9]+"
      - path: $.orderCharacteristic.[?(@.name=='orderCreationDate')].value
        type: by_regex
        predefined: iso_date_time
      - path: $.orderCharacteristic.[?(@.name=='Project_Manager_Required')].value
        type: by_regex
        value: '(Yes|No)'
      - path: $.orderCharacteristic.[?(@.name=='Project_ID')].value
        type: by_regex
        value: "[A-Za-z0-9]+"
      - path: $.orderCharacteristic.[?(@.name=='orderComplexity')].value
        type: by_regex
        value: '(Simple|Complex)'
      - path: $.orderItem[0].id
        type: by_regex
        value: '[a-z0-9\-\|]+'
      - path: $.orderItem[0].product.id
        type: by_regex
        value: '[a-z0-9\-\|]+'
      - path: $.orderItem[1].id
        type: by_regex
        value: '[a-z0-9\-\|]+'
      - path: $.orderItem[1].product.id
        type: by_regex
        value: '[a-z0-9\-\|]+'
response:
  status: 200
  body:  # (9)
    "status": "OK"
  headers: # (10)
    Content-Type: application/json;charset=UTF-8`

**Comment by marcingrzejszczak** [comment]
Can you please format the code?

**Comment by KanikaDeka** [comment]
> Can you please format the code?

Not getting any shortcuts to format.

**Comment by marcingrzejszczak** [comment]
Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

**Comment by KanikaDeka** [comment]
> Please learn how to [properly format the code](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

done.. :-). Thanks

**Comment by marcingrzejszczak** [comment]
Ok, wait for 20 minutes or so, and please try with the latest snapshots. Then you'll be able to create such a contract with request and response matchers:

```groovy
org.springframework.cloud.contract.spec.Contract.make {
				request {
					method 'POST'
					urlPath '/get'
					body([
							duck: 123,
							alpha: "abc",
							number: 123,
							aBoolean: true,
							date: "2017-01-01",
							dateTime: "2017-01-01T01:23:45",
							time: "01:02:34",
							valueWithoutAMatcher: "foo",
							valueWithTypeMatch: "string",
							list: [
								some: [
									nested: [
										json: "with value",
										anothervalue: 4
									]
								],
								someother: [
									nested: [
										json: "with value",
										anothervalue: 4
									]
								]
							],
							valueWithMin: [
								1,2,3
							],
							valueWithMax: [
								1,2,3
							],
							valueWithMinMax: [
								1,2,3
							]
					])
					bodyMatchers {
						jsonPath('$.duck', byRegex("[0-9]{3}"))
						jsonPath('$.duck', byEquality())
						jsonPath('$.alpha', byRegex(onlyAlphaUnicode()))
						jsonPath('$.alpha', byEquality())
						jsonPath('$.number', byRegex(number()))
						jsonPath('$.aBoolean', byRegex(anyBoolean()))
						jsonPath('$.date', byDate())
						jsonPath('$.dateTime', byTimestamp())
						jsonPath('$.time', byTime())
						jsonPath('$.list.some.nested.json', byRegex(".*"))
						jsonPath('$.valueWithMin', byType {
							// results in verification of size of array (min 1)
							minOccurrence(1)
						})
						jsonPath('$.valueWithMax', byType {
							// results in verification of size of array (max 3)
							maxOccurrence(3)
						})
						jsonPath('$.valueWithMinMax', byType {
							// results in verification of size of array (min 1 & max 3)
							minOccurrence(1)
							maxOccurrence(3)
						})
						jsonPath('$.valueWithOccurrence', byType {
							// results in verification of size of array (min 4 & max 4)
							occurrence(4)
						})
					}
					headers {
						contentType(applicationJson())
					}
				}
				response {
					status OK()
					body([
							duck: 123,
							alpha: "abc",
							number: 123,
							aBoolean: true,
							date: "2017-01-01",
							dateTime: "2017-01-01T01:23:45",
							time: "01:02:34",
							valueWithoutAMatcher: "foo",
							valueWithTypeMatch: "string",
							valueWithMin: [
								1,2,3
							],
							valueWithMax: [
								1,2,3
							],
							valueWithMinMax: [
								1,2,3
							],
							valueWithOccurrence: [
								1,2,3,4
							],
					])
					bodyMatchers {
						// asserts the jsonpath value against manual regex
						jsonPath('$.duck', byRegex("[0-9]{3}"))
						jsonPath('$.duck', byEquality())
						// asserts the jsonpath value against some default regex
						jsonPath('$.alpha', byRegex(onlyAlphaUnicode()))
						jsonPath('$.alpha', byEquality())
						jsonPath('$.number', byRegex(number()))
						jsonPath('$.aBoolean', byRegex(anyBoolean()))
						// asserts vs inbuilt time related regex
						jsonPath('$.date', byDate())
						jsonPath('$.dateTime', byTimestamp())
						jsonPath('$.time', byTime())
						// asserts that the resulting type is the same as in response body
						jsonPath('$.valueWithTypeMatch', byType())
						jsonPath('$.valueWithMin', byType {
							// results in verification of size of array (min 1)
							minOccurrence(1)
						})
						jsonPath('$.valueWithMax', byType {
							// results in verification of size of array (max 3)
							maxOccurrence(3)
						})
						jsonPath('$.valueWithMinMax', byType {
							// results in verification of size of array (min 1 & max 3)
							minOccurrence(1)
							maxOccurrence(3)
						})
						jsonPath('$.valueWithOccurrence', byType {
							// results in verification of size of array (min 4 & max 4)
							occurrence(4)
						})
					}
					headers {
						contentType(applicationJson())
					}
				}
			}
```

**Comment by marcingrzejszczak** [comment]
And the yaml version

```yml
request:
  method: GET
  urlPath: /get/1
  headers:
    Content-Type: application/json
  cookies:
    foo: 2
    bar: 3
  queryParameters:
    limit: 10
    offset: 20
    filter: 'email'
    sort: name
    search: 55
    age: 99
    name: John.Doe
    email: 'bob@email.com'
  body:
    duck: 123
    alpha: "abc"
    number: 123
    aBoolean: true
    date: "2017-01-01"
    dateTime: "2017-01-01T01:23:45"
    time: "01:02:34"
    valueWithoutAMatcher: "foo"
    valueWithTypeMatch: "string"
    key:
      "complex.key": 'foo'
    nullValue: null
    valueWithMin:
      - 1
      - 2
      - 3
    valueWithMax:
      - 1
      - 2
      - 3
    valueWithMinMax:
      - 1
      - 2
      - 3
    valueWithMinEmpty: []
    valueWithMaxEmpty: []
  matchers:
    url:
      regex: /get/[0-9]
      # predefined:
      # execute a method
      #command: 'equals($it)'
    queryParameters:
      - key: limit
        type: equal_to
        value: 20
      - key: offset
        type: containing
        value: 20
      - key: sort
        type: equal_to
        value: name
      - key: search
        type: not_matching
        value: '^[0-9]{2}$'
      - key: age
        type: not_matching
        value: '^\\w*$'
      - key: name
        type: matching
        value: 'John.*'
      - key: hello
        type: absent
    cookies:
      - key: foo
        regex: '[0-9]'
      - key: bar
        command: 'equals($it)'
    headers:
      - key: Content-Type
        regex: "application/json.*"
    body:
      - path: $.duck
        type: by_regex
        value: "[0-9]{3}"
      - path: $.duck
        type: by_equality
      - path: $.alpha
        type: by_regex
        predefined: only_alpha_unicode
      - path: $.alpha
        type: by_equality
      - path: $.number
        type: by_regex
        predefined: number
      - path: $.aBoolean
        type: by_regex
        predefined: any_boolean
      - path: $.date
        type: by_date
      - path: $.dateTime
        type: by_timestamp
      - path: $.time
        type: by_time
      - path: "$.['key'].['complex.key']"
        type: by_equality
      - path: $.nullvalue
        type: by_null
      - path: $.valueWithMin
        type: by_type
        minOccurrence: 1
      - path: $.valueWithMax
        type: by_type
        maxOccurrence: 3
      - path: $.valueWithMinMax
        type: by_type
        minOccurrence: 1
        maxOccurrence: 3
response:
  status: 200
  cookies:
    foo: 1
    bar: 2
  body:
    duck: 123
    alpha: "abc"
    number: 123
    aBoolean: true
    date: "2017-01-01"
    dateTime: "2017-01-01T01:23:45"
    time: "01:02:34"
    valueWithoutAMatcher: "foo"
    valueWithTypeMatch: "string"
    valueWithMin:
      - 1
      - 2
      - 3
    valueWithMax:
      - 1
      - 2
      - 3
    valueWithMinMax:
      - 1
      - 2
      - 3
    valueWithMinEmpty: []
    valueWithMaxEmpty: []
    key:
      'complex.key' : 'foo'
    nulValue: null
  matchers:
    headers:
      - key: Content-Type
        regex: "application/json.*"
    cookies:
      - key: foo
        regex: '[0-9]'
      - key: bar
        command: 'equals($it)'
    body:
      - path: $.duck
        type: by_regex
        value: "[0-9]{3}"
      - path: $.duck
        type: by_equality
      - path: $.alpha
        type: by_regex
        predefined: only_alpha_unicode
      - path: $.alpha
        type: by_equality
      - path: $.number
        type: by_regex
        predefined: number
      - path: $.aBoolean
        type: by_regex
        predefined: any_boolean
      - path: $.date
        type: by_date
      - path: $.dateTime
        type: by_timestamp
      - path: $.time
        type: by_time
      - path: $.valueWithTypeMatch
        type: by_type
      - path: $.valueWithMin
        type: by_type
        minOccurrence: 1
      - path: $.valueWithMax
        type: by_type
        maxOccurrence: 3
      - path: $.valueWithMinMax
        type: by_type
        minOccurrence: 1
        maxOccurrence: 3
      - path: $.valueWithMinEmpty
        type: by_type
        minOccurrence: 0
      - path: $.valueWithMaxEmpty
        type: by_type
        maxOccurrence: 0
      - path: $.duck
        type: by_command
        value: assertThatValueIsANumber($it)
      - path: $.nullValue
        type: by_null
        value: null
  headers:
    Content-Type: application/json
```
