### ISSUE TITLE
Missing bodyFromFileAsBytes for YAML contracts

### ISSUE THREAD

**Issue by benoitheinrich** [spring-cloud/spring-cloud-contract#835]
Bug report

I'm using the following versions:
- spring-boot 2.1.0.RELEASE
- spring-cloud-contract 2.1.0.M2

I've created a yaml contract as follow:
```
description: |
  Export current configuration

name: exportConfiguration
request:
  url: /configurations/export
  method: GET

response:
  status: 200
  headers:
    Content-Type: application/zip
    Content-Disposition: "attachment; filename=configuration.zip"
  bodyFromFileAsBytes: exit101.zip
```

Build fails with the following error:
```
[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.0.M2:convert (default-convert) on project api: Execution default-convert of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:2.1.0.M2:convert failed: Failed to convert file [.../api/src/test/resources/contracts/vm/ui/shouldConfigurationExport.yaml]: Exception occurred while processing the file [.../api/src/test/resources/contracts/vm/ui/shouldConfigurationExport.yaml]: Unrecognized field "bodyFromFileAsBytes" (class org.springframework.cloud.contract.verifier.converter.YamlContract$Response), not marked as ignorable (9 known properties: "matchers", "status", "metaClass", "headers", "bodyFromFile", "async", "cookies", "fixedDelayMilliseconds", "body"])
[ERROR]  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.springframework.cloud.contract.verifier.converter.YamlContract["response"]->org.springframework.cloud.contract.verifier.converter.YamlContract$Response["bodyFromFileAsBytes"])
```

Based on the documentation I should be able to use the `bodyFromFileAsBytes`:
https://cloud.spring.io/spring-cloud-contract/single/spring-cloud-contract.html#contract-dsl-passing-values-from-files

Can you please let me know if I'm doing something wrong ?

Thanks.
