### ISSUE TITLE
bodyFromFileAsBytes failing with FileNotFoundException

### ISSUE THREAD

**Issue by benoitheinrich** [spring-cloud/spring-cloud-contract#836]
Bug report

I'm using spring-cloud-contract 2.1.0.RC3

I've created a yaml contract as follow:
```
description: |
  Export current configuration

name: exportConfiguration
request:
  url: /configurations/export
  method: GET

response:
  status: 200
  headers:
    Content-Type: application/zip
    Content-Disposition: "attachment; filename=configuration.zip"
  bodyFromFileAsBytes: exit101.zip
```

The generated test asserts the file content using the following which seems exact:
```
			assertThat(response.getBody().asByteArray()).isEqualTo(fileToBytes(this, "exportConfiguration_response_exit101.zip"));
```

Build fails with the following error:
```
[ERROR]   UiTest.validate_exportConfiguration:32 » IllegalState java.io.FileNotFoundException: exportConfiguration_response_exit101.zip
```

I've created a test project that reproduce this issue here: https://github.com/benoitheinrich/spring-cloud-contract-zip-sample

Can you please let me know if I'm doing something wrong ?

Thanks.
