### ISSUE TITLE
Stubs are not registered in Eureka service discovery

### ISSUE THREAD

**Issue by fezu54** [spring-cloud/spring-cloud-contract#838]
I am trying to register my stubs from the producer in a Eureka service discovery for smoke testing purposes. Therefore I created a jar from the following setup, which fetches the stubs from a maven repository. The stub runner itself is successfully registered in the service discovery, but the endpoint of the stubs are not reachable via the url provided by the API gateway. 
The only way I can call the stubs is by their own url which is of course not working during the smoke tests. Is there something I totally misunderstood?

Setup:

```
@SpringBootApplication
@EnableStubRunnerServer
@EnableEurekaClient
@AutoConfigureStubRunner
class EurekaStubRunnerApplication

fun main(args: Array<String>) {
    runApplication<EurekaStubRunnerApplication>(*args)
}
```
bootstrap.yml

```
spring:
  application:
    name: masterdata
jhipster:
  registry:
    password: admin
```

application.yml

```
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: false
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
  instance:
    appname: masterdata
    instance-id: masterdata:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: management/info
    health-check-url-path: management/health
ribbon:
  eureka:
    enabled: true
server:
  port: 8888
stubrunner:
  cloud:
    eureka:
      enabled: true
    stubbed:
      discovery:
        enabled: true
```
I am starting the jar with the following command:
`java -jar eureka-stub-runner-0.0.1-SNAPSHOT.jar --stubrunner.ids=com.xetics.mes:masterdata-stubs:+:8081 --stubrunner.stubsMode=LOCAL`

Calling the endpoint via the gateway of the real microservice is working:
```
curl -X GET --header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU0NjYxMDc2OH0.EF3PHho-B-ayOmmeFrcA90U38cd3AZsU7pA7-9xN0SpuVBvev2sHvejv-FI_FlrwP7qWcCpibW-yWwFDBSUv9w' 'http://localhost:8080/masterdata/api/stations'
[]
```

Whereas calling the same endpoint of the registered stub runner is not working:
```
curl -X GET --header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU0NjYxMDc2OH0.EF3PHho-B-ayOmmeFrcA90U38cd3AZsU7pA7-9xN0SpuVBvev2sHvejv-FI_FlrwP7qWcCpibW-yWwFDBSUv9w' 'http://localhost:8080/masterdata/api/stations'
{"timestamp":"2019-01-03T16:59:36.426+0000","status":404,"error":"Not Found","message":"No message available","path":"/api/stations"}
```

Calling the stubs directly is working:
```
curl -X GET --header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOLFJPTEVfVVNFUiIsImV4cCI6MTU0NjYxMDc2OH0.EF3PHho-B-ayOmmeFrcA90U38cd3AZsU7pA7-9xN0SpuVBvev2sHvejv-FI_FlrwP7qWcCpibW-yWwFDBSUv9w' 'http://localhost:8081/api/stations'
[{"archiveTime":null,"description":"A fantastic base for building a time machine","id":1985,"maxCapacity":2,"name":"DeLorean DMC 12","icon":"delorean-icon"},{"archiveTime":null,"description":"A handy tool for manipulating the space time continuum","id":2015,"maxCapacity":1,"name":"Flux capacitor"}]
```

Is it somehow possible to register the stubs in a way I can call them via the endpoint of the API gateway, or is this simply not possible?

Just to be open, I've also ask the same question on stackoverflow: https://stackoverflow.com/questions/54026743/how-to-make-spring-cloud-stubrunner-boot-register-stubs-in-eureka-discovery
