### ISSUE TITLE
Spring Cloud Contract - Spring Kafka

### ISSUE THREAD

**Issue by Jenani-Srinivasan** [spring-cloud/spring-cloud-contract#877]
As per the discussion with Marcin on Twitter, Spring Cloud Contract does not have implementation to support pure Spring Kafka Template.  As, there is no feature for spring cloud contract to support spring kafka template.

Can I please request to have the implementation?

**Comment by IrishkA13** [comment]
Is there any plans when it will be done?

**Comment by OlgaMaciaszek** [comment]
Hello, it's in the backlog @IrishkA13 and it will  be done; will try to add it for Hoxton release.

**Comment by marcingrzejszczak** [comment]
I think I have a prototype working. Does anyone have a sample I could play with?

**Comment by pszymczyk** [comment]
@jakubnabrdalik

**Comment by mfolnovic** [comment]
@IrishkA13 2.2.0.M3, so I assume it goes to future release `2.2.0.RELEASE` (so it's not released yet, just `M3`)

**Comment by IrishkA13** [comment]
@mfolnovic thanks for reply
Are there any planned dates for 2.2.0.RELEASE?

**Comment by marcingrzejszczak** [comment]
Please check https://github.com/spring-cloud/spring-cloud-release/milestones for release dates

**Comment by DawidSwinoga** [comment]
Hi!

I added one field to your sample kafka contract.

`Contract.make {
	label("trigger")
	input {
		triggeredBy("trigger()")
	}
	outputMessage {
		sentTo("topic1")
		body([
		        foo: 'example',
			bar: 'example2'
		])
	}
}`

and change application-test.yaml (consumer side)
`spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    producer:
      properties:
        "value.serializer": "org.springframework.kafka.support.serializer.JsonSerializer"
        "spring.json.trusted.packages": "*"
    consumer:
      properties:
        "value.deserializer": "org.springframework.kafka.support.serializer.JsonDeserializer"
        "value.serializer": "org.springframework.kafka.support.serializer.JsonSerializer"
        "spring.json.trusted.packages": "*"
      group-id: groupId`

I also add "bar" field to Foo2 class on the consumer side. Now if I run the ApplicationTests on the consumer side I have exception like this: 
`Caused by: org.springframework.kafka.support.converter.ConversionException: Failed to convert from JSON; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.common.Foo2` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"foo":"example","bar":"example2"}')
 at [Source: (String)""{\"foo\":\"example\",\"bar\":\"example2\"}""; line: 1, column: 1]`

This exception is caused by:
- extra " sign at the start and end of the message
- backslashes


When I add this hack everythinks works. Is there any other way to solve this?
`	@Bean
	@Primary
	public RecordMessageConverter converter() {
		return new StringJsonMessageConverter() {
			@Override
			protected Object convertPayload(Message<?> message) {
//				return super.convertPayload(message);
				String value = (String) super.convertPayload(message);
				if (value.length() > 2 && value.startsWith("\"") && value.endsWith("\"")) {
					value = value.substring(1, value.length() - 1);

				}
				return StringEscapeUtils.unescapeJson(value); //apache commons
			}
		};
	}`

**Comment by marcingrzejszczak** [comment]
I think I had a similar issue so to speak. In the tests (https://github.com/spring-cloud/spring-cloud-contract/tree/master/tests/spring-cloud-contract-stub-runner-kafka), what I did was:

application.yml
```yml
spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    producer:
      properties:
        "value.serializer": "org.springframework.kafka.support.serializer.JsonSerializer"
        "spring.json.trusted.packages": "*"
    consumer:
      properties:
        "value.deserializer": "org.springframework.kafka.support.serializer.JsonDeserializer"
        "value.serializer": "org.springframework.kafka.support.serializer.JsonSerializer"
        "spring.json.trusted.packages": "*"
      group-id: ${random.value}
```

that's how I received the message

```groovy
private boolean assertThatBodyContainsBookNameFoo(Object payload) {
		log.info("Got payload [" + payload + "]")
		String objectAsString = payload instanceof String ? payload :
				JsonOutput.toJson(payload)
		def json = new JsonSlurper().parseText(objectAsString)
		return json.bookName == 'foo'
	}
```

I'm no Kafka expert, so maybe what I did is just a hack. I guess we would need to ask @olegz , @sobychacko or @garyrussell for help if what I did is actually a hack .
